### ISSUE TITLE
duties record book / system specification

### ISSUE THREAD

**Issue by stampFabian** [AdamKITZ/SWP_Fabi-Adam#182]

**Comment by AdamKITZ** [comment]
what is this

**Comment by stampFabian** [comment]
[Duties Record Book _ Adam & Fabian.docx](https://github.com/AdamKITZ/SWP_Fabi-Adam/files/10488707/Duties.Record.Book._.Adam.Fabian.docx)

**Comment by stampFabian** [comment]
[Duties Record Book _ Adam & Fabian.docx](https://github.com/AdamKITZ/SWP_Fabi-Adam/files/10488735/Duties.Record.Book._.Adam.Fabian.docx)
small changes (language)
